name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies with poetry
        run: |
          pip install poetry
          poetry install

      - run: poetry run isort --recursive --diff .
      - run: poetry run black --check .
      - run: poetry run flake8
      - run: poetry run mypy
      - run: poetry run pytest --cov # --cov-fail-under=90
      - name: Test building docker image
        run: docker build . -t bot_sylwek
      - name: Clear app directory
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.REMOTE_PASSWORD }}
            script: rm -rf www && mkdir -p www/app
      - name: Clear app directory
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.REMOTE_PASSWORD }}
            script: rm -rf www && mkdir -p www/app
      - name: Clear app directory
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.REMOTE_PASSWORD }}
            script: rm -rf www && mkdir -p www/app
      - name: rsync
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: "/home/github-actions/www/app"
      - name: Run application
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.REMOTE_PASSWORD }}
            script: cd "www/app" && echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env && docker build -t bot-sylwek . && docker-compose up -d
